<script setup lang="ts">
const route=useRoute();const supabase=useSupabaseClient();const sw=ref<any>(null);const ports=ref<any[]>([]);const points=ref<any[]>([]);const vlans=ref<any[]>([]);const show=ref(false);const editId=ref<string|null>(null);const form=reactive<any>({port_number:null,data_point_id:'',device_connection:'',device_name:'',vlan_id:null,vlan_name:'',port_mode:'Untagged',patch_lead_colour:'',status:'Active',change_required:false,tested_after_patching:false,date_tested:'',technician:'',notes:''})
async function load(){const id=route.params.id as string;const [{data:s},{data:p},{data:d},{data:v}]=await Promise.all([supabase.from('switches').select('*').eq('id',id).single(),supabase.from('switch_ports').select('*, data_points(data_point_code)').eq('switch_id',id).order('port_number'),supabase.from('data_points').select('id,data_point_code,building,room').order('data_point_code'),supabase.from('vlans').select('*').order('vlan_id')]);sw.value=s;ports.value=p||[];points.value=d||[];vlans.value=v||[]}
function add(){editId.value=null;Object.assign(form,{port_number:null,data_point_id:'',device_connection:'',device_name:'',vlan_id:null,vlan_name:'',port_mode:'Untagged',patch_lead_colour:'',status:'Active',change_required:false,tested_after_patching:false,date_tested:'',technician:'',notes:''});show.value=true}
function edit(r:any){editId.value=r.id;Object.assign(form,r,{data_point_id:r.data_point_id||'',date_tested:r.date_tested||''});show.value=true}
function vlanChanged(){const v=vlans.value.find(x=>x.vlan_id===form.vlan_id);form.vlan_name=v?.vlan_name||''}
async function save(){const payload={...form,switch_id:route.params.id,data_point_id:form.data_point_id||null,date_tested:form.date_tested||null};editId.value?await supabase.from('switch_ports').update(payload).eq('id',editId.value):await supabase.from('switch_ports').insert(payload);if(payload.data_point_id)await supabase.from('data_points').update({switch_id:route.params.id,switch_port:String(form.port_number)}).eq('id',payload.data_point_id);show.value=false;await load()}
async function del(r:any){if(confirm(`Delete port ${r.port_number} mapping?`)){await supabase.from('switch_ports').delete().eq('id',r.id);await load()}}onMounted(load)
</script><template><section v-if="sw"><div class="pagehead"><div><NuxtLink to="/switches">← Switches</NuxtLink><h2>{{sw.switch_code}} — {{sw.name}}</h2><p>{{sw.building}} · {{sw.room_cabinet}} · {{sw.management_ip||'No management IP'}}</p></div><button class="btn" @click="add">+ Map Port</button></div><div class="tablewrap"><table><thead><tr><th>Port</th><th>Data Point</th><th>Device</th><th>VLAN</th><th>Mode</th><th>Status</th><th>Tested</th><th></th></tr></thead><tbody><tr v-for="r in ports" :key="r.id"><td><strong>{{r.port_number}}</strong></td><td>{{r.data_points?.data_point_code||'—'}}</td><td>{{r.device_name||r.device_connection||'—'}}</td><td>{{r.vlan_id||'—'}} {{r.vlan_name}}</td><td>{{r.port_mode||'—'}}</td><td><span class="badge">{{r.status}}</span></td><td>{{r.tested_after_patching?'Yes':'No'}}</td><td class="nowrap"><button class="link" @click="edit(r)">Edit</button> <button class="link danger" @click="del(r)">Delete</button></td></tr><tr v-if="!ports.length"><td colspan="8" class="empty">No ports mapped yet.</td></tr></tbody></table></div><AppModal v-if="show" title="Switch Port" @close="show=false"><form class="formgrid" @submit.prevent="save"><label>Port Number<input v-model.number="form.port_number" type="number" min="1" required></label><label>Data Point<select v-model="form.data_point_id"><option value="">None</option><option v-for="d in points" :value="d.id">{{d.data_point_code}} — {{d.building}} {{d.room}}</option></select></label><label>Device / Connection<input v-model="form.device_connection"></label><label>Device Name<input v-model="form.device_name"></label><label>VLAN<select v-model.number="form.vlan_id" @change="vlanChanged"><option :value="null">None</option><option v-for="v in vlans" :value="v.vlan_id">{{v.vlan_id}} — {{v.vlan_name}}</option></select></label><label>Port Mode<select v-model="form.port_mode"><option>Untagged</option><option>Tagged</option><option>Trunk</option></select></label><label>Patch Lead Colour<input v-model="form.patch_lead_colour"></label><label>Status<select v-model="form.status"><option>Active</option><option>Unused</option><option>Disabled</option><option>Fault</option></select></label><label><input v-model="form.change_required" type="checkbox"> Change required</label><label><input v-model="form.tested_after_patching" type="checkbox"> Tested after patching</label><label>Date Tested<input v-model="form.date_tested" type="date"></label><label>Technician<input v-model="form.technician"></label><label class="full">Notes<textarea v-model="form.notes"></textarea></label><div class="full right"><button class="btn secondary" type="button" @click="show=false">Cancel</button> <button class="btn">Save</button></div></form></AppModal></section></template>
