<script setup lang="ts">
const supabase=useSupabaseClient();const route=useRoute();const rows=ref<any[]>([]);const campuses=ref<any[]>([]);const show=ref(false);const editId=ref<string|null>(null);const q=ref('');const campusFilter=ref(String(route.query.campus||''));const form=reactive<any>({switch_code:'',name:'',campus_id:'',building:'',room_cabinet:'',make_model:'',management_ip:'',management_vlan:null,uplink_port:'',uplink_to:'',firmware:'',notes:''})
async function load(){const [{data:r},{data:c}]=await Promise.all([supabase.from('switches').select('*, campuses(name,code)').order('building').order('switch_code'),supabase.from('campuses').select('id,name,code').eq('active',true).order('name')]);rows.value=r||[];campuses.value=c||[]}
function blank(){return {switch_code:'',name:'',campus_id:campusFilter.value||'',building:'',room_cabinet:'',make_model:'',management_ip:'',management_vlan:null,uplink_port:'',uplink_to:'',firmware:'',notes:''}}
function add(){editId.value=null;Object.assign(form,blank());show.value=true}function edit(r:any){editId.value=r.id;Object.assign(form,r,{campus_id:r.campus_id||''});show.value=true}
async function save(){if(!form.campus_id)return alert('Please select a campus. Every switch must belong to a campus.');const payload={...form,campus_id:form.campus_id||null,management_ip:form.management_ip||null,management_vlan:form.management_vlan||null};delete payload.campuses;const {error}=editId.value?await supabase.from('switches').update(payload).eq('id',editId.value):await supabase.from('switches').insert(payload);if(error)return alert(error.message);show.value=false;await load()}
async function del(r:any){if(confirm(`Delete ${r.switch_code}? Its switch ports will also be deleted.`)){const {error}=await supabase.from('switches').delete().eq('id',r.id);if(error)return alert(error.message);await load()}}
const filtered=computed(()=>rows.value.filter(r=>(!campusFilter.value||r.campus_id===campusFilter.value)&&`${r.switch_code} ${r.name} ${r.campuses?.name||''} ${r.building||''} ${r.room_cabinet||''} ${r.management_ip||''}`.toLowerCase().includes(q.value.toLowerCase())));onMounted(load)
</script><template><section><div class="pagehead"><div><h2>Switch Inventory</h2><p>Switches are separated by campus. Select a campus to view only that network.</p></div><button class="btn" @click="add">+ Add Switch</button></div><div class="filterbar"><select v-model="campusFilter"><option value="">All Campuses</option><option v-for="c in campuses" :key="c.id" :value="c.id">{{c.name}}</option></select><input v-model="q" class="search" placeholder="Search switches…"></div><div class="tablewrap"><table><thead><tr><th>Campus</th><th>Switch</th><th>Location</th><th>Model</th><th>Management</th><th>Uplink</th><th></th></tr></thead><tbody><tr v-for="r in filtered" :key="r.id"><td><span class="badge">{{r.campuses?.name||'Unassigned'}}</span></td><td><NuxtLink :to="`/switches/${r.id}`"><strong>{{r.switch_code}}</strong><br><small>{{r.name}}</small></NuxtLink></td><td>{{r.building||'—'}}<br><small>{{r.room_cabinet}}</small></td><td>{{r.make_model||'—'}}</td><td>{{r.management_ip||'—'}}<br><small>VLAN {{r.management_vlan||'—'}}</small></td><td>{{r.uplink_port||'—'}} → {{r.uplink_to||'—'}}</td><td class="nowrap"><button class="link" @click="edit(r)">Edit</button> <button class="link danger" @click="del(r)">Delete</button></td></tr><tr v-if="!filtered.length"><td colspan="7" class="empty">No switches found for this campus.</td></tr></tbody></table></div><AppModal v-if="show" title="Switch" @close="show=false"><form class="formgrid" @submit.prevent="save"><label>Campus<select v-model="form.campus_id" required><option value="" disabled>Select campus…</option><option v-for="c in campuses" :key="c.id" :value="c.id">{{c.name}}</option></select></label><label>Switch ID<input v-model="form.switch_code" required></label><label>Name<input v-model="form.name" required></label><label>Building<input v-model="form.building"></label><label>Room / Cabinet<input v-model="form.room_cabinet"></label><label>Make / Model<input v-model="form.make_model"></label><label>Management IP<input v-model="form.management_ip"></label><label>Management VLAN<input v-model.number="form.management_vlan" type="number"></label><label>Firmware<input v-model="form.firmware"></label><label>Uplink Port<input v-model="form.uplink_port"></label><label>Uplink To<input v-model="form.uplink_to"></label><label class="full">Notes<textarea v-model="form.notes"></textarea></label><div class="full right"><button type="button" class="btn secondary" @click="show=false">Cancel</button> <button class="btn">Save</button></div></form></AppModal></section></template>
