<script setup lang="ts">
const supabase=useSupabaseClient();const rows=ref<any[]>([]);const show=ref(false);const editId=ref<string|null>(null);const form=reactive<any>({name:'',code:'',address:'',notes:'',active:true})
async function load(){const {data}=await supabase.from('campuses').select('*').order('name');rows.value=data||[]}
function add(){editId.value=null;Object.assign(form,{name:'',code:'',address:'',notes:'',active:true});show.value=true}
function edit(r:any){editId.value=r.id;Object.assign(form,r);show.value=true}
async function save(){const payload={name:form.name,code:form.code||null,address:form.address||null,notes:form.notes||null,active:form.active};const {error}=editId.value?await supabase.from('campuses').update(payload).eq('id',editId.value):await supabase.from('campuses').insert(payload);if(error)return alert(error.message);show.value=false;await load()}
async function del(r:any){if(confirm(`Delete campus ${r.name}? Switches and data points will become unassigned.`)){const {error}=await supabase.from('campuses').delete().eq('id',r.id);if(error)return alert(error.message);await load()}}
onMounted(load)
</script>
<template><section><div class="pagehead"><div><h2>Campuses</h2><p>Create the campuses used to separate the network map.</p></div><button class="btn" @click="add">+ Add Campus</button></div><div class="campusgrid"><div v-for="r in rows" :key="r.id" class="panel campuscard"><div><h3>{{r.name}}</h3><p><b>{{r.code||'No code'}}</b><br>{{r.address||'No address entered'}}</p></div><div><NuxtLink class="btn tiny" :to="`/switches?campus=${r.id}`">View Switches</NuxtLink> <button class="link" @click="edit(r)">Edit</button> <button class="link danger" @click="del(r)">Delete</button></div></div></div><div v-if="!rows.length" class="panel empty">No campuses yet. Add your first campus to begin separating the network map.</div><AppModal v-if="show" title="Campus" @close="show=false"><form class="formgrid" @submit.prevent="save"><label>Campus Name<input v-model="form.name" required placeholder="e.g. Brigidine Campus"></label><label>Campus Code<input v-model="form.code" placeholder="e.g. BRG"></label><label class="full">Address<input v-model="form.address"></label><label class="full">Notes<textarea v-model="form.notes"></textarea></label><label><input v-model="form.active" type="checkbox"> Active</label><div class="full right"><button type="button" class="btn secondary" @click="show=false">Cancel</button> <button class="btn">Save</button></div></form></AppModal></section></template>
