<script setup lang="ts">
const supabase=useSupabaseClient(); const rows=ref<any[]>([]); const show=ref(false); const editId=ref<string|null>(null); const q=ref(''); const form=reactive<any>({switch_code:'',name:'',building:'',room_cabinet:'',make_model:'',management_ip:'',management_vlan:null,uplink_port:'',uplink_to:'',firmware:'',notes:''})
async function load(){const {data}=await supabase.from('switches').select('*').order('building').order('switch_code');rows.value=data||[]}
function add(){editId.value=null;Object.assign(form,{switch_code:'',name:'',building:'',room_cabinet:'',make_model:'',management_ip:'',management_vlan:null,uplink_port:'',uplink_to:'',firmware:'',notes:''});show.value=true}
function edit(r:any){editId.value=r.id;Object.assign(form,r);show.value=true}
async function save(){const payload={...form,management_ip:form.management_ip||null,management_vlan:form.management_vlan||null}; editId.value?await supabase.from('switches').update(payload).eq('id',editId.value):await supabase.from('switches').insert(payload);show.value=false;await load()}
async function del(r:any){if(confirm(`Delete ${r.switch_code}? Its switch ports will also be deleted.`)){await supabase.from('switches').delete().eq('id',r.id);await load()}}
const filtered=computed(()=>rows.value.filter(r=>`${r.switch_code} ${r.name} ${r.building} ${r.room_cabinet} ${r.management_ip||''}`.toLowerCase().includes(q.value.toLowerCase())));onMounted(load)
</script><template><section><div class="pagehead"><div><h2>Switch Inventory</h2><p>Manage network switches and open a switch to map its ports.</p></div><button class="btn" @click="add">+ Add Switch</button></div><input v-model="q" class="search" placeholder="Search switches…"><div class="tablewrap"><table><thead><tr><th>Switch</th><th>Location</th><th>Model</th><th>Management</th><th>Uplink</th><th></th></tr></thead><tbody><tr v-for="r in filtered" :key="r.id"><td><NuxtLink :to="`/switches/${r.id}`"><strong>{{r.switch_code}}</strong><br><small>{{r.name}}</small></NuxtLink></td><td>{{r.building}}<br><small>{{r.room_cabinet}}</small></td><td>{{r.make_model||'—'}}</td><td>{{r.management_ip||'—'}}<br><small>VLAN {{r.management_vlan||'—'}}</small></td><td>{{r.uplink_port||'—'}} → {{r.uplink_to||'—'}}</td><td class="nowrap"><button class="link" @click="edit(r)">Edit</button> <button class="link danger" @click="del(r)">Delete</button></td></tr><tr v-if="!filtered.length"><td colspan="6" class="empty">No switches found.</td></tr></tbody></table></div><AppModal v-if="show" title="Switch" @close="show=false"><form class="formgrid" @submit.prevent="save"><label>Switch ID<input v-model="form.switch_code" required></label><label>Name<input v-model="form.name" required></label><label>Building<input v-model="form.building"></label><label>Room / Cabinet<input v-model="form.room_cabinet"></label><label>Make / Model<input v-model="form.make_model"></label><label>Management IP<input v-model="form.management_ip"></label><label>Management VLAN<input v-model.number="form.management_vlan" type="number"></label><label>Firmware<input v-model="form.firmware"></label><label>Uplink Port<input v-model="form.uplink_port"></label><label>Uplink To<input v-model="form.uplink_to"></label><label class="full">Notes<textarea v-model="form.notes"></textarea></label><div class="full right"><button type="button" class="btn secondary" @click="show=false">Cancel</button> <button class="btn">Save</button></div></form></AppModal></section></template>
